version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:5.7
    volumes:
      - /home/maaz/mysql/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    networks:
      - wordpress_network

  # WordPress Service
  wordpress:
    image: wordpress:latest
    ports:
      - "8084:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    networks:
      - wordpress_network
    volumes:
      - /home/maaz/wordpress/wp-content:/var/www/html

networks:
  wordpress_network:
    driver: bridge

volumes:
  db_data:
  wp_data:
